# This is a basic workflow to help you get started with Actions

name: CI WebGoat Veracode

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven -y
      - name: Setting up OpenJDK 15
        run: |
          wget https://download.java.net/java/GA/jdk15.0.1/51f4f36ad4ef43e39d0dfdbaf6549e32/9/GPL/openjdk-15.0.1_linux-x64_bin.tar.gz
          sudo mkdir /usr/lib/java
          sudo tar -xvf openjdk-15.0.1_linux-x64_bin.tar.gz -C /usr/lib/java
          export PATH=$PATH:/usr/lib/java/jkd-15.0.1/bin
          export JAVA_HOME="/usr/lib/java/jdk-15.0.1"
          sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/java/jdk-15.0.1/bin/java" 0
          sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/java/jdk-15.0.1/bin/javac" 0 
          sudo update-alternatives --install "/usr/bin/javap" "javap" "/usr/lib/java/jdk-15.0.1/bin/javap" 0
          sudo update-alternatives --set java /usr/lib/java/jdk-15.0.1/bin/java
          sudo update-alternatives --set javac /usr/lib/java/jdk-15.0.1/bin/javac
          sudo update-alternatives --set javap /usr/lib/java/jdk-15.0.1/bin/javap
      - name: Checking JAVA Version and Environment
        run: |
          java -version
          echo $PATH
          echo $JAVA_HOME
      - name: Compiling project
        run: |
          export PATH=$PATH:/usr/lib/java/jkd-15.0.1/bin
          export JAVA_HOME="/usr/lib/java/jdk-15.0.1"
          mvn -e clean install
          
  software-composition-analisys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master        
    - shell: bash
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: |
        export SRCCLR_SCM_URI="https://github.com/lucasferreiram3/WebGoat-Java.git"
        export SRCCLR_SCM_REF=${{ github.workflow }}
        export SRCCLR_SCM_REF_TYPE="branch"
        export SRCCLR_SCM_REV=${{ github.run_id }}
        
        export EXTRA_ARGS='--update-advisor'
        curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS
          
